### ISSUE TITLE
Getting UnicodeDecode error

### ISSUE THREAD

**Issue by eldracode** [facebook-developer-circle-delhi/Meetups#10]
While reading the .csv file in pandas I am getting the UnicodeDecode Error : 
``df = pd.read_csv('path/train.csv')``

when I used this : 
``df = pd.read_csv('path/train.csv',encoding='utf-8')``

I am still getting error

**Comment by shreybatra** [comment]
Yes, you may be using python > version 3.6

Just add *r* before the path... like

```df = pd.read_csv(r'some_path/cc.csv')```
