### ISSUE TITLE
Security vulnerabilities in packages of react resources

### ISSUE THREAD

**Issue by saranshkataria** [facebook-developer-circle-delhi/Meetups#13]
There are 2 known vulnerabilities in packages since the project has not been updated recently. Need to update the dependency tree

![image](https://user-images.githubusercontent.com/1450819/45937591-21c57100-bfdf-11e8-8406-44843c49efb1.png)

**Comment by saranshkataria** [comment]
@Ankk98's PR fixes this issue, closing this out

**Comment by Ankk98** [comment]
Thanks, @saranshkataria for beginner issue.

**Comment by Ankk98** [comment]
#15

**Comment by saranshkataria** [comment]
@Ankk98 just doing my bit to help people. Also, next time please mention the issue number in the PR
