### ISSUE TITLE
GraphQl Talk

### ISSUE THREAD

**Issue by siddhant1** [facebook-developer-circle-delhi/Meetups#17]
From 0 to Graphql
I will be talking about graphql basics , starting from 0 to establishing a base of graphQL , then moving to Prisma and then establishing frontend with React and Apollo
30 minutes
It will be a mixture of session and hands on
Basic knowledge of async Javascript
Siddhant (twitter : @siddhant6969)
Any time except my exams.

**Comment by harshitjuneja** [comment]
Let's get into the details over call. Next meetup is on 29th December.

**Comment by siddhant1** [comment]
Sure

**Comment by harshitjuneja** [comment]
Proposal accepted for 29th December 2018 meetup. Closing the issue.
