### ISSUE TITLE
Bundling Javascript :Webpack

### ISSUE THREAD

**Issue by aloksingh3112** [facebook-developer-circle-delhi/Meetups#18]
Webpack : It's just a Module Bundler
I will be covering webpack  from the basics to most of the term use in webpack and do live coding on webpack config file for react
40-50  min 
it will be mixture of both session and hands on
basic knowledge of  javascript
Alok Kumar Singh (@Aloksin16818071)
whole year except my exams

**Comment by harshitjuneja** [comment]
Talk is confirmed for 29th December. Closing the issue.
