### ISSUE TITLE
Google Protocol Buffers and Live Demo

### ISSUE THREAD

**Issue by shreybatra** [facebook-developer-circle-delhi/Meetups#19]
**Google Protocol Buffers and Live Demo**
**Intro:** What, why to use Protobufs and how is it better than JSON. How to integrate it with regular flask/django apps and live demo of using or showcasing it.
**Talk Duration:** 1 hour
**Type of Talk:** Hands-on/Talk
**Prerequisites for talk:** Basics of python, basics of JSON objects, basics of flask would be good.
**About yourself:** Machine Learning Workshop in past

**Comment by harshitjuneja** [comment]
We have an open spot for 25th Jan. Please update on your avialability.
