### ISSUE TITLE
Difference Between Open Source Mailing System and Normal Mailing System 

### ISSUE THREAD

**Issue by Ishaan28malik** [facebook-developer-circle-delhi/Meetups#25]
**IMAP and POP**
**Intro:** So the talk is about the difference between open source mailing system like Zimbra and Gmail.
**Talk Duration:** 20-25 min
**Type of Talk:** Session
**Prerequisites for talk:** Basics of Protocols 
**About yourself:** Talk on Using Git and Open Source

**Comment by harshitjuneja** [comment]
Could be a flash talk. @Ishaan28malik let me know if first week November would be okay for you.

**Comment by harshitjuneja** [comment]
Closing because of no updates from the speaker.

**Comment by Ishaan28malik** [comment]
Alright, not an issue.I will update you once I am in town for the talk.
Thanks for understanding @harshitjuneja .
