### ISSUE TITLE
Data Visualization using seaborn 

### ISSUE THREAD

**Issue by Ishaan28malik** [facebook-developer-circle-delhi/Meetups#27]
**Introduction to Seaborn**
**How to use Seaborn for data visualization**
**20 min**
**Session/Hands-on**
**Basic knowledge of Python**
**I am undergrad student and a researcher worked with IBMcloud**
[ Previous Talks](https://youtu.be/OAvn4k95tVs)

**Comment by harshitjuneja** [comment]
Get ready for March 10th. 👍

**Comment by harshitjuneja** [comment]
Closing this issue, since the talk didn't happen earlier and a better description is needed now.

**Comment by Ishaan28malik** [comment]
Ok 
So let's see what I can plan for the next meetup. I do have a plan for a talk on  Open Source Mail.
