### ISSUE TITLE
Talk title: Commit to Git

### ISSUE THREAD

**Issue by prankshaw** [facebook-developer-circle-delhi/Meetups#28]
**Commit to Git **
**Talk Description:** _Understanding git, need of version control system, how to use git, Hands on to committing changes and making a pull request. Managing large software development. How and from where to start open source journey and related perks/swags. Intro to Continuous Integration, continuous deployment and delivery._  
**12-15 minutes**
**Type of Talk: (Session)**
**Prerequisites for talk:** _Git Bash downloaded and account on GitHub(preferably)_
**Link  to slides:** _Under development, will post soon_
**About yourself:** I _am Pranjal Rastogi, a computer science undergrad and Have experience working as data scientist. I have contributed to various open source projects and currently mentoring  data science project as well._
**March, April**

**Comment by harshitjuneja** [comment]
Git and version control would be something too beginner for our audience. Would you be able to give a talk focussed on CI & CD?

**Comment by prankshaw** [comment]
Ok, I am thinking about some uncommon issues handled using git and CI/ CD intro, but I will require some time to prepare. If meet-up is on 9th/10th , I will be happy to give a talk, but might be difficult on 2nd, but will try

**Comment by harshitjuneja** [comment]
Hey @prankshaw. Any updates on the CI/CD topic?

**Comment by prankshaw** [comment]
I am sorry, I can, but I am busy now and might not be available to give a talk😪. I will definitely try to give a talk at the next meetup.

**Comment by harshitjuneja** [comment]
Hey @prankshaw. Any updates on the CI/CD topic?

**Comment by prankshaw** [comment]
Hi,
I am sorry, but I am out of the city now and won't be able to deliver a talk.
