### ISSUE TITLE
Blockchain and ICO

### ISSUE THREAD

**Issue by Akash-sh** [facebook-developer-circle-delhi/Meetups#29]
**Talk Title: Blockchain and ICO **
**Talk Description: a brief introduction to wonderful technology of blockchain, how it works, a touch of blockchain 3.0, how ICOs are affecting the startup ventures and much morr **
**Talk Duration: **
**Type of Talk: 20 minutes (Session)**
**Prerequisites for talk: (if any)**
**Link  to slides: will provide soon after confirmation**
**Aboutyourself: https://www.linkedin.com/in/akash-sharma-b68a41123 **
**Months available to speak: No limits**

**Comment by Akash-sh** [comment]
Upon having experience to speak at multiple occasions such Paytm: Build for India, College  Events and Startup Meets, both nationally as well as internationally. I'm quite interested to step into Facebook developer circle to share some wisdom as well as gain some.

**Comment by harshitjuneja** [comment]
Looks good. Your talk is accepted for the meetup on 10th March.

**Comment by Akash-sh** [comment]
Can you please provide some details about the meet scheduled for March 10th, will very much appreciate it. Thanks.

**Comment by pratikgujral** [comment]
Hey Akash, the registration page shall be live soon. The venue for the March '19 meetup is CoWrks, Delhi Aerocity. You'll have an approximately 15-minute slot to present your talk.

**Comment by Akash-sh** [comment]
Thanks for the Information, See you guys on 10th!
