### ISSUE TITLE
Intro to React Hooks

### ISSUE THREAD

**Issue by siddhant1** [facebook-developer-circle-delhi/Meetups#31]
**Talk Title: *intro to React hooks*
**Talk Description: *In this talk I will be discussing about the newly released feature of react , ie react hooks, we will be introducing all the hooks and explaining some of them , then in the end I will discuss how to make custom hooks*
**Talk Duration: *30-35 minutes*
**Type of Talk: (Session/Hands-on/Workshop) *I prefer hands on for this but can also give a talk*
**Prerequisites for talk: (if any) Basic knowledge of react
**Link  to slides:**
**About yourself: (Include links to previous talks if you have given any) :- intro to  Graphql and flash intro to hooks

**Comment by harshitjuneja** [comment]
See you on 10th March with  hooks.
