### ISSUE TITLE
Coding For Scalability - Flash Talk

### ISSUE THREAD

**Issue by shreybatra** [facebook-developer-circle-delhi/Meetups#32]
**Talk Title:** Coding For Scalability - Flash Talk
**Talk Description:** Scalability in Software Development, practises and norms.
**Talk Duration:** 30 min
**Type of Talk: (Session/Hands-on/Workshop)** Session
**Prerequisites for talk: (if any)** Coding experience
**About yourself: (Include links to previous talks if you have given any)** ML Session.
**Months available to speak:** March 10th.

**Comment by harshitjuneja** [comment]
See you on 10th March.

**Comment by shreybatra** [comment]
Got to reschedule this one for the next meetup.

**Comment by harshitjuneja** [comment]
@shreybatra We have a spot in our November FB Live. Let me know if it works for you and we can discuss further.

**Comment by harshitjuneja** [comment]
Closing because of no updates from the speaker.
