### ISSUE TITLE
Talk Title: Best optimisation techniques with React

### ISSUE THREAD

**Issue by nik72619c** [facebook-developer-circle-delhi/Meetups#33]
**Talk Title:** Best optimisation techniques with React 
**Talk Description:** In this talk I would cover the following-
1. Lazy loading and profiling using React DevTools
2. Concept of "windowing" in react
3. Significance of shouldComponentUpdate 
4. Removing unnecessary renders using React.memo
5. Reconciliation -under the hood
**Talk Duration:** 40-45 mins
**Type of Talk:Session**
**Prerequisites for talk: Basic knowledge of React*
**Link  to slides:** Not ready yet
**About yourself: (Include links to previous talks if you have given any)** Blogger | OSS Contributor | MERN stack developer | Speaker | Build scalable reactive apps with React and Node
github:- nik72619c
twitter: @niksharma1997
link to my talk at React Delhi NCR:-https://slides.com/nik72619c/react-delhi-ncr-portals#
More about me:- type npx nik72619c in the terminal

**Comment by nik72619c** [comment]
Would remove Reconciliation or make it brief to chop the time to 30 mins

**Comment by harshitjuneja** [comment]
Nice talk. Closing.
