### ISSUE TITLE
Airflow : automating your data pipelines

### ISSUE THREAD

**Issue by uday1201** [facebook-developer-circle-delhi/Meetups#34]
**Talk Title: Airflow: automating your data pipelines**
**Talk Description:We will be talking about apache airflow and how it can be used to automate data pipelines by creating DAGs of our jobs.**
**Talk Duration: 20-30 minutes**
**Type of Talk: Hands-on**
**Prerequisites for talk: None**
**Link  to slides: To be added**
**About yourself: Talk on introduction to machine learning in FDC**
**Months available to speak: March**

**Comment by harshitjuneja** [comment]
See you at the event.

**Comment by harshitjuneja** [comment]
@uday1201 We've got a spot in our November meetup. Does it work for you?

**Comment by harshitjuneja** [comment]
Closing since it's been pending for a while.
