### ISSUE TITLE
Design Thinking

### ISSUE THREAD

**Issue by thakurpallavi** [facebook-developer-circle-delhi/Meetups#35]
**Title:**  Design Thinking
**Description:** We will talk about a way of thinking that can facilitate and structure one's natural creativity to come up with solutions to all kinds of problems, not just design and have fun in the process too
**Duration:**  20-30 minutes
**Type of Talk:** Interactive session
**Prerequisites for talk:** None
**Link to slides:** To be worked upon
**About yourself:** Computer science graduate, currently working as a UI/UX Designer. Facilitated a variety of hands-on learning experiences introducing school students to the field of designing.
**Months available to speak:** March, April

**Comment by harshitjuneja** [comment]
Closing the issue. See you on 9th March
