### ISSUE TITLE
GraphQL and REST

### ISSUE THREAD

**Issue by AvaniVerma** [facebook-developer-circle-delhi/Meetups#36]
**Talk Title:** GraphQL and REST API
**Talk Description:** The talk will start by covering what is graphQL and REST,What benefits are offered by each of them. And what does it mean for developers. Is it time we should stop RESTing and join the graphQl bandwagon ?
**Talk Duration:** ~15 minutes
**Type of Talk:** Session
**Prerequisites for talk:** None
**Link  to slides:** Working on them
**About yourself:** I am a fourth year undergraduate at NSUT, pursuing computer engineering. For more, please visit   [Avani](https://avaniverma.github.io/)  
**Months available to speak:** March

**Comment by harshitjuneja** [comment]
See you on 9th March. Closing the issue.
