### ISSUE TITLE
Ballerina a cloud native language

### ISSUE THREAD

**Issue by jaisadana19** [facebook-developer-circle-delhi/Meetups#37]
**Talk Title: **
**Talk Description: **
**Talk Duration: **
**Type of Talk: (Session/Hands-on/Workshop)**
**Prerequisites for talk: (if any)**
**Link  to slides:**
**About yourself: (Include links to previous talks if you have given any)**
**Months available to speak:**

**Comment by harshitjuneja** [comment]
Duplicate issue, closing this one.

**Comment by jaisadana19** [comment]
Ok
