### ISSUE TITLE
Ballerina (Cloud Native Language)

### ISSUE THREAD

**Issue by jaisadana19** [facebook-developer-circle-delhi/Meetups#38]
**Talk Title: ballerina 
**Talk Description: introduction to ballerina and it’s uses 
**Talk Duration: 2hr - 2.5 hr
**Type of Talk: workshop 
**Prerequisites for talk: none 
**Link  to slides:in development right now 
**About yourself: I am a developer who seeks to learn something new and share that practical experiences with other 
**Months available to speak: 8-9 Months

**Comment by harshitjuneja** [comment]
@jaisadana19 A better description about the talk topic is needed. Closing the issue for now.
