### ISSUE TITLE
Security: From Shields to Bunkers

### ISSUE THREAD

**Issue by gaurav-gogia** [facebook-developer-circle-delhi/Meetups#44]
**Talk Title:** 
Security: From Shields to Bunkers

**Talk Description:**
An introductory session into cybersecurity. Idea is to bust myths around this domain & bring everyone closer to the real picture as much as possible by including a hands-on session on threat modelling.

**Talk Duration:**
100 - 130 Minutes

**Timeline:**
1. Myth-busting: 
**Time:** 5 - 10 Minutes

2. Security as an umbrella term
**Time:** 5 - 10 Minutes

3. Domains in Security
- VAPT
- Incident Response
- Forensics
- Malware Analysis
- Cyber Law
**Time:** 5 Minutes each

4. Secure SDLC: Security for every developer.
**Time**: 5 - 10 Minutes

5. Hands-On Threat Modelling
**Time:** 30-45 Minutes

**Type of Talk: (Session/Hands-on/Workshop)**
Hands-on

**Prerequisites for the talk: (if any)**
Any laptop

**Link  to slides:**
[Shields to Bunkers](https://vips0-my.sharepoint.com/:p:/g/personal/03029802015_vips_edu/EWAAx3MVRpdCvBlxx5S9peQBneTkcEYF7SwAQFZNh1u62Q)

**About yourself: (Include links to previous talks if you have given any)**
MSc DFIS Student, interned in a couple of startups. 

**Months available to speak:**
One

**Comment by saranshkataria** [comment]
Thanks for the talk @gaurav-gogia!
