### ISSUE TITLE
One shot learning

### ISSUE THREAD

**Issue by raviranjan0631** [facebook-developer-circle-delhi/Meetups#48]
Talk Title: One Shot Learning : Face Recognition
Talk Description:We will be talking about Neural Network,  One Shot Learning,  and built a face recognition project using one shot learning
Talk Duration: 50:60 minutes
Type of Talk: Hands-on
Prerequisites for talk: None
Link to slides: To be added
About yourself: Facebook Deep Learning Facilitator
Months available to speak: August

**Comment by harshitjuneja** [comment]
@raviranjan0631 Let us know if you would want to give this talk on 2nd November.

**Comment by raviranjan0631** [comment]
I will be available on 2nd of november for the talk

**Comment by harshitjuneja** [comment]
Is the time enough? @pratikgujral would you want to pair with @raviranjan0631 and maybe take the other half?

**Comment by raviranjan0631** [comment]
I will need approx 1.5 hours or both lecture and hands-on session

**Comment by harshitjuneja** [comment]
Talk is finalized for 10th Nov. Hence, closing this issue.
