### ISSUE TITLE
Indexing with description

### ISSUE THREAD

**Issue by vabhishek-me** [facebook-developer-circle-delhi/Meetups#5]
Hey @saranshkataria, I think we should index the readme with the meetup details like what was discussed and links to the repo contents.....

I'm willing to do it but I'll need your help for meetup details.

What do you think?

**Comment by saranshkataria** [comment]
Indexing as in?

**Comment by vabhishek-me** [comment]
Something like

## Meetups

#### XYZ Date
 - Some description about the meetup / what was discusses / maybe who was the speaker
 - Resources:
    - ABC
    - DEF

**Comment by vabhishek-me** [comment]
And *ABC* *DEF* will link to the specific folder with the resources...

**Comment by saranshkataria** [comment]
Again, as with the other repo, that will become too large with time. Do we have a better way of keeping it short? Need to brainstorm on this a bit

**Comment by vabhishek-me** [comment]
I don't think this will become too large.... there are a lot of repos who keep indexing for better navigation. The main goal of our repo is for people to find resources and I think indexing will help them.

And once the meetup is over, we can add the info and then its' done. We won't have to touch it again.

Like for example check these out:
https://github.com/tbarn/austin-tech-meetups
https://github.com/michaeljones/elm-manchester-resources

**Comment by saranshkataria** [comment]
The links that you have mentioned are relatively small ones. Since we have at least one meetup a month, this might get out of hands quickly. Though I did like the table format and that seems like a good idea

**Comment by vabhishek-me** [comment]
So we can keep a header with the list of meetups that links to details at the bottom........ like the *awesome-xyz* repos do

**Comment by saranshkataria** [comment]
Since we would be having a splash URL for every meetup which will have the details for it, I think the way https://github.com/tbarn/austin-tech-meetups has done it makes sense for us too

**Comment by vabhishek-me** [comment]
Great! So, I'll update the readme and will do a pull request soon

**Comment by harshitjuneja** [comment]
@vabhishek-me are you on it?

**Comment by vabhishek-me** [comment]
@saranshkataria I'll need the links for meetups to update..... rest is done....

**Comment by vabhishek-me** [comment]
Should we add facebook events page for each meetups?

**Comment by vabhishek-me** [comment]
done - check the pull request
