### ISSUE TITLE
Lightning Talk: Techniques to Ensure Individual Privacy when Drawing Business Insights from Consumer Data

### ISSUE THREAD

**Issue by festusdrakon** [facebook-developer-circle-delhi/Meetups#52]
**Talk Title:** Techniques to Ensure Individual Privacy when Drawing Business Insights from Customer Data
**Talk Description:** Give an overview of the process of business insight extraction from customer data using standard analytics platforms and discuss how individual privacy is maintained by using techniques such as Differential Privacy and Federated Learning   
**Talk Duration:** 12 minutes
**Type of Talk: (Session/Hands-on/Workshop)** Lightning Talk
**Prerequisites for talk: (if any)** None
**About yourself: (Include links to previous talks if you have given any)** I have 5 years of freelance experience with strategizing and implementing digital marketing campaigns for small scale startups and so have been at that end of the pipeline where we were required to draw business insights from standard website metrics to optimize performance of advertising campaigns and deliver services to our intended audience. I have also worked as a content creator and truly understand the value of privacy and strive always to fiercely protect it. I am also a Facebook Secure and Private AI Challenge Scholar and so have been educated about the technical latticework behind customer privacy through the program, and look forward to sharing that knowledge with the extended developer ecosystem at large. Look forward to seeing you at the talk! ^-^

**Comment by harshitjuneja** [comment]
Closing, since we should be able to accommodate a few lightning talks in any of our upcoming meetups.
