### ISSUE TITLE
#IamRemarkable Workshop

### ISSUE THREAD

**Issue by Ambika55** [facebook-developer-circle-delhi/Meetups#61]
**Talk Title: **  #IamRemarkable 
**Talk Description: **  #IamRemarkable is an initiative empowering women and underrepresented groups to speak openly about their accomplishments in the workplace and beyond, thereby breaking modesty norms and glass ceilings. To learn more and join the initiative visit: g.co/IamRemarkable
**Talk Duration: **  Around 90 mins
**Type of Talk: (Session/Hands-on/Workshop)**  Workshop
**Prerequisites for talk: (if any)** writing sheets and pens
**Link  to slides:** don't have public access 
**About yourself: (Include links to previous talks if you have given any)** All my talks are available on my LinkedIn profile https://www.linkedin.com/in/ambika55/
**Months available to speak:** January, February

**Comment by harshitjuneja** [comment]
Looks good. The tentative event date is 25th Jan. @pratikgujral anything to add in here?

**Comment by harshitjuneja** [comment]
@Ambika55 This has been pending for a while. Can we take this session as a FB Live?

**Comment by Ambika55** [comment]
I don't know if we are allowed to take it live but we can take it with the
audience who are interested. But for taking it online I have first ask them
and see what they say about the no. of audience. Give me some time I will
ask them wheather I can take it as a live session or not.

**Comment by harshitjuneja** [comment]
Hello @Ambika55 ,

Did we get a positive response on this? Happy to hear updates if any.

**Comment by harshitjuneja** [comment]
Closing because of no updates.
