### ISSUE TITLE
Flutter vs React Native : From Newbies Perspective

### ISSUE THREAD

**Issue by Kaushl2208** [facebook-developer-circle-delhi/Meetups#62]
**Talk Title: Flutter vs React Native : From Newbies Perspective**

**Talk Description:** Our main aim is to develop interest about Flutter and React-native. Through this talk we are trying to describe the basic differences between two technologies by a hands-on which includes building a common simple application by Flutter and React-Native. Followed by the approaches one can know to adapt any of these technologies.

**Talk Duration:** 1 hr 30 min (max)

**Type of Talk:** (Session/Hands-on)

**Prerequisites for talk:**  JavaScript, Dart, [DartPad](https://dartpad.dev/) and [Snack](https://snack.expo.io/)

**Link  to slides:** Will be updated after talk

**About yourself:**
I(Kaushlendra Pratap), am a junior year computer science student at Amity University. This workshop will be conducted by me and my colleague Sahil. He is also a junior year computer science student and React developer at Appventurez.

**Social Links to your profile**

Kaushlendra Pratap - https://linkedin.com/in/kaushl2208
Sahil Jha - https://linkedin.com/in/sjha2048

Recently, we have delivered a talk on VUI. The link to the proposal is given below:
https://github.com/asetalias/Logistics-and-Event-Contributions/issues/35

**Months available to speak:** Free anytime except March.

**Comment by harshitjuneja** [comment]
Looks good. Since it's a hands-on session. It's better to mention the software/libraries people would need as well in the pre-requisites.

**Comment by harshitjuneja** [comment]
@pratikgujral Anything to add in here?

**Comment by Kaushl2208** [comment]
@harshitjuneja we plan to use online tools so there is no need for specific software/libraries.

**Comment by apoorvtomar2222** [comment]
@Kaushl2208 Yes you can tell about the online tool, so that person who is willing to attend the session can get the idea of platform you're planning to use.

**Comment by Kaushl2208** [comment]
@apoorvtomar2222 I have updated the prerequisities section.

**Comment by apoorvtomar2222** [comment]
@Kaushl2208  Sure.

**Comment by harshitjuneja** [comment]
Thanks for talk people. Closing this issue.
