### ISSUE TITLE
Introduction to CNNs

### ISSUE THREAD

**Issue by yashika51** [facebook-developer-circle-delhi/Meetups#63]
**Talk Title: ** Introduction to CNNs
**Talk Description: ** This talk will introduce the audience to convolutional neural networks and will be beginners friendly.We won't go much over the maths(not to scare them) and will try to explain as much as possible using the theory.
**Talk Duration: **30-40 mins
**Type of Talk: (Session/Hands-on/Workshop)** Session
**Prerequisites for talk: (if any)** Some knowledge of arrays, vectors, and matrices
**Link  to slides:** 
**About yourself: (Include links to previous talks if you have given any)** I have previously given a  talk on getting started with NumPy on the women who code python platform but the recording has not released yet.Find more about me here- https://www.linkedin.com/in/yashikasharma5174/ . Twitter- @yashika51
**Months available to speak:** February,March

**Comment by harshitjuneja** [comment]
Hello @yashika51 .

We have a spot available for May/June. Would want to know about your availability.

cc: @pratikgujral

**Comment by yashika51** [comment]
Hi @harshitjuneja, I am available after mid-june.

**Comment by harshitjuneja** [comment]
Does 20th June work for you. Also will the talk content be the same as mentioned above? If no, can you please update the content by adding a new comment in this thread.

**Comment by harshitjuneja** [comment]
Closing because of no updates. If you are up for the talk, please open a new issue with the updated months available to speak. Thank you for taking time to raise the issue.
