### ISSUE TITLE
How to tame your malware

### ISSUE THREAD

**Issue by gaurav-gogia** [facebook-developer-circle-delhi/Meetups#65]
**Talk Title:**
How to tame your malware

**Talk Description:**
Have you ever wanted to write your own Anti Virus or Firewall or were you just curious about how one works? Or maybe you just want to better protect yourself and those around you? Look no further. We'll take on this topics through some hands-on analysis.
 
**Talk Duration:**
30 - 45 Minutes

**Type of Talk: (Session/Hands-on/Workshop)**
Hands-on

**Prerequisites for talk: (if any)**
Please make sure you have following software installed:
1. [YARA](https://virustotal.github.io/yara)
2. [Any hex editor (Recommended: 010 Editor)](https://www.sweetscape.com/download/010editor/)
3. [VS Code (Recommended)](https://code.visualstudio.com/Download)

**Link  to slides:**
1. [WHAT IS MALWARE ANALYSIS? DEFINING AND OUTLINING THE PROCESS OF MALWARE ANALYSIS](https://digitalguardian.com/blog/what-malware-analysis-defining-and-outlining-process-malware-analysis)
2. [Practical Malware Analysis](https://www.blackhat.com/presentations/bh-dc-07/Kendall_McMillan/Presentation/bh-dc-07-Kendall_McMillan.pdf)
3. [Malware Analysis: An Introduction](https://www.sans.org/reading-room/whitepapers/malicious/malware-analysis-introduction-2103)
4. [Introduction to Malware Analysis](https://www.youtube.com/watch?v=f-fMdnUW4X4)
5. [Malware Analysis SIG](https://www.first.org/global/sigs/malware/)

**About yourself: (Include links to previous talks if you have given any)**
I am Gaurav Gogia, currently studying MSc Digital Forensics in Gujarat Forensic Sciences University. My interests revolve around security, games and anime. Not particularly in that order. My idea of learnning security is from a blue team's perspective. It is to try and build things instead of the more popular penetration testing. 

**Months available to speak:**
3

**Comment by saranshkataria** [comment]
@gaurav-gogia I doubt we would be having an offline meetup anytime soon. Do you plan to do this as an online event instead?

**Comment by gaurav-gogia** [comment]
@saranshkataria yes, online event sounds good. I talked to @harshitjuneja he said that one online event is planned, so I created an issue here.

**Comment by harshitjuneja** [comment]
Finalized for FB live on 2nd of May @ 12 noon. Closing the issue.

Thanks @gaurav-gogia :)
