### ISSUE TITLE
Intro to Serverless: Demystify the cloud

### ISSUE THREAD

**Issue by JamieDawson** [facebook-developer-circle-delhi/Meetups#74]
**Talk Title: **  Intro to Serverless: Demystify the cloud
**Talk Description: ** In just 1 hour you'll learn all the things you'll need to launch serverless apps to the cloud. The best part is that we'll only have to focus on code logic and nothing else. When you download the Nimbella serverless platform for free, everything you need is available right out of the box. All the services you'd normally have to set up are handled for you when you deploy the code to the cloud. So all you focus on is code logic and we handle the rest.  
**Talk Duration: ** 1 hour
**Type of Talk: (Session/Hands-on/Workshop)**:   Session.
**Prerequisites for talk: (if any)**:  None. 
**Link  to slides:**     https://docs.google.com/presentation/d/1SziTM0CQq71VtbpUlgvvhFYyAEYrgFIpe3hwblUIVUg/edit?usp=sharing
**About yourself: (Include links to previous talks if you have given any)** I'm a Dev Advocate for Nimbella. Before Nimbella I was an intern at Samsung for the Bixby Premier Developer Program where I helped the top 100 Bixby developer build apps. I was also a K-12  teacher in an after school program called CodeForFun where I taught how to be a software developer. I'm also an alumnus at a programmer school called 42 Silicon Valley. 
**Months available to speak:** Sept, Oct, Nov, Dec

**Comment by harshitjuneja** [comment]
Thanks, Jamie for taking the time to raise the PR.

The event will take place on Sept 12, 11 AM in the FB group.

If there's a setup/software requried for people to follow along. Please let us know and we'll include it in the invites. :)

**Comment by harshitjuneja** [comment]
Talk confirmed. Closing the issue.
